---
abstract: 'Load and binding for Tcl/Tk IWidgets-Library'
author:
  - 'Jürgen von Brietzke <brietzkej@t-online.de>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tkx-TclTk-Bind-IWidgets
no_index:
  directory:
    - t
    - inc
requires:
  Env::C: 0
  Tkx::TclTk::Bind: 0
version: v1.2.01
